import {
  Activity,
  AlignVerticalDistributeCenter,
  Anchor,
  ArrowDown,
  ArrowDownUp,
  ArrowUp,
  AudioWaveform,
  BarChart,
  BarChart2,
  BarChart3,
  Blocks,
  Box,
  Boxes,
  CircleEllipsis,
  Clock,
  Cloud,
  Crosshair,
  Flag,
  Gauge,
  GitBranch,
  GitCommitVertical,
  Hexagon,
  Layers,
  LineChart,
  Magnet,
  Mountain,
  Scaling,
  Shapes,
  Shield,
  TrendingUp,
  Triangle,
  Waves,
  Zap,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

const BLOCK_NAME_ICON: Record<string, LucideIcon> = {
  'Adaptive Momentum Oscillator': AudioWaveform,
  'Adr':                           Activity,
  'Adx':                           TrendingUp,
  'Anchored Vwap':                 Anchor,
  'Ascending Triangle':            Triangle,
  'Asfx A2 Vwap':                  Anchor,
  'Asia Session 50 Percent':       Clock,
  'Atr':                           Activity,
  'Balanced Price Range':          Scaling,
  'Bollinger Bands':               BarChart2,
  'Break Of Structure':            GitBranch,
  'Breaker Block':                 Boxes,
  'Candle 2 Close':                BarChart3,
  'Change Of Character':           GitBranch,
  'Cup And Handle':                CircleEllipsis,
  'Descending Triangle':           Triangle,
  'Displacement':                  Zap,
  'Double Bottom':                 ArrowDown,
  'Double Top':                    ArrowUp,
  'Elliott Wave Count':            Waves,
  'Elliott Wave Oscillator':       Waves,
  'Ema 20 50 Cross':               GitCommitVertical,
  'Ema 20 50 Trend':               LineChart,
  'Ema 200 Trend':                 LineChart,
  'Ema 255 Vector':                LineChart,
  'Ema 50 Vector':                 LineChart,
  'Ema 55 Vector':                 LineChart,
  'Ema 800 Vector':                LineChart,
  'Ema Crossover':                 GitCommitVertical,
  'Fair Value Gap':                Scaling,
  'Falling Wedge':                 Triangle,
  'Fibonacci Retracements':        AlignVerticalDistributeCenter,
  'Fifty Pct Hod Lod':             Magnet,
  'Fifty Pct Intra Hod Lod':       Magnet,
  'Flag Pattern':                  Flag,
  'Head And Shoulders':            Hexagon,
  'Hod':                           ArrowUp,
  'How':                           ArrowUp,
  'Ichimoku Cloud':                Cloud,
  'Ict Silver Bullet':             Crosshair,
  'Ihod':                          ArrowUp,
  'Ilod':                          ArrowDown,
  'Inducement':                    Magnet,
  'Initial Balance Breakout':      Box,
  'Internal Pivot Pattern':        GitBranch,
  'Inverse Head And Shoulders':    Hexagon,
  'Kill Zones':                    Crosshair,
  'Liquidity':                     Layers,
  'Liquidity Sweep':               Layers,
  'Lod':                           ArrowDown,
  'Low':                           ArrowDown,
  'Macd Price Forecasting':        LineChart,
  'Macd Signal':                   LineChart,
  'Market Depth':                  Layers,
  'Market Structure Shift':        GitBranch,
  'Mitigation Block':              Boxes,
  'Optimal Trade Entry':           Crosshair,
  'Order Block':                   Boxes,
  'Order Flow Imbalance':          Scaling,
  'Pennant Pattern':               Flag,
  'Power Hour Trends':             Zap,
  'Premium Discount Zones':        Layers,
  'Range Liquidity':               Layers,
  'Rising Wedge':                  Triangle,
  'Rounding Bottom':               CircleEllipsis,
  'Rsi Divergence':                Gauge,
  'Session Time':                  Clock,
  'Stochastic Rsi':                Gauge,
  'Supply Demand Zones':           Layers,
  'Swing Breakout Sequence':       GitBranch,
  'Swing Failure Pattern':         GitBranch,
  'Swing Points':                  GitBranch,
  'Symmetrical Triangle':          Triangle,
  'Three Bar Reversal':            ArrowDownUp,
  'Trailing Stop':                 Shield,
  'Triple Bottom':                 ArrowDown,
  'Triple Top':                    ArrowUp,
  'Us Settlement':                 Clock,
  'Vwap':                          Anchor,
  'Wave Consolidation':            Waves,
  'Wyckoff Accumulation':          BarChart,
  'Wyckoff Distribution':          BarChart,
  'Wyckoff Reaccumulation':        BarChart,
};

const CATEGORY_ICON: Record<string, LucideIcon> = {
  ELLIOTT_WAVE:     Waves,
  FIBONACCI:        AlignVerticalDistributeCenter,
  INSTITUTIONAL:    Mountain,
  MARKET_STRUCTURE: GitBranch,
  MOVING_AVERAGES:  LineChart,
  OSCILLATORS:      AudioWaveform,
  PATTERNS:         Shapes,
  PRICE_ACTION:     Scaling,
  PRICE_LEVELS:     Magnet,
  RISK_MANAGEMENT:  Shield,
  SESSIONS:         Clock,
  SIGNALS:          Crosshair,
  SMC_ICT:          Boxes,
  SUPPLY_DEMAND:    Layers,
  TREND:            TrendingUp,
  VOLATILITY:       Activity,
  WYCKOFF:          BarChart,
};

export function resolveBlockIcon(name: string, category: string): LucideIcon {
  return BLOCK_NAME_ICON[name] ?? CATEGORY_ICON[category?.toUpperCase()] ?? Blocks;
}
