import {
  Activity,
  ActivitySquare,
  AlignVerticalDistributeCenter,
  Anchor,
  ArrowBigDown,
  ArrowBigUp,
  ArrowDown,
  ArrowDownUp,
  ArrowUp,
  Atom,
  AudioLines,
  AudioWaveform,
  BarChart,
  BarChart2,
  BarChart3,
  BarChart4,
  Blocks,
  Bolt,
  Boxes,
  CandlestickChart,
  ChevronDown,
  ChevronUp,
  CircleArrowDown,
  CircleArrowUp,
  CircleDot,
  CircleEllipsis,
  Clock,
  Cloud,
  Compass,
  Contrast,
  CornerDownLeft,
  CornerUpRight,
  Crosshair,
  Dna,
  Droplets,
  Flag,
  FlagTriangleRight,
  FlipHorizontal,
  Focus,
  Footprints,
  Gauge,
  GitBranch,
  GitCommitVertical,
  GitFork,
  GitGraph,
  GitMerge,
  Goal,
  Hammer,
  Hexagon,
  Infinity,
  Layers,
  Layers2,
  Layers3,
  LineChart,
  Lock,
  Magnet,
  Maximize2,
  Milestone,
  Mountain,
  Pause,
  Pin,
  Pyramid,
  Radar,
  Ratio,
  Scale,
  Scaling,
  Shapes,
  Shield,
  Shuffle,
  Sigma,
  Signal,
  Slash,
  SlidersHorizontal,
  Spline,
  Sunrise,
  Sunset,
  Target,
  Thermometer,
  TrendingDown,
  TrendingUp,
  Triangle,
  Wand,
  Waves,
  Wind,
  Zap,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

// Every value in this record MUST be unique — the board prohibits icon reuse across
// the 83 Strategy Builder building blocks (BTCAAAAA-29972). The dev assertion below
// fails loudly if a future edit reintroduces a duplicate.
const BLOCK_NAME_ICON: Record<string, LucideIcon> = {
  'Adaptive Momentum Oscillator': AudioWaveform,
  'Adr':                           Activity,
  'Adx':                           TrendingUp,
  'Anchored Vwap':                 Anchor,
  'Ascending Triangle':            Triangle,
  'Asfx A2 Vwap':                  Pin,
  'Asia Session 50 Percent':       Sunrise,
  'Atr':                           Thermometer,
  'Balanced Price Range':          Scale,
  'Bollinger Bands':               BarChart2,
  'Break Of Structure':            GitBranch,
  'Breaker Block':                 Hammer,
  'Candle 2 Close':                CandlestickChart,
  'Change Of Character':           GitFork,
  'Cup And Handle':                CircleEllipsis,
  'Descending Triangle':           TrendingDown,
  'Displacement':                  Zap,
  'Double Bottom':                 ArrowBigDown,
  'Double Top':                    ArrowBigUp,
  'Elliott Wave Count':            Waves,
  'Elliott Wave Oscillator':       ActivitySquare,
  'Ema 20 50 Cross':               GitCommitVertical,
  'Ema 20 50 Trend':               LineChart,
  'Ema 200 Trend':                 Spline,
  // EMA Vector blocks use non-directional icons per board feedback on BTCAAAAA-29972
  // (2026-05-26): directional arrows mislead the user — EMAs continuously move both up
  // and down, so the icon must not imply a fixed direction.
  'Ema 255 Vector':                Dna,
  'Ema 50 Vector':                 AudioLines,
  'Ema 55 Vector':                 Atom,
  'Ema 800 Vector':                Infinity,
  'Ema Crossover':                 Shuffle,
  'Fair Value Gap':                Scaling,
  'Falling Wedge':                 CornerDownLeft,
  'Fibonacci Retracements':        AlignVerticalDistributeCenter,
  'Fifty Pct Hod Lod':             Magnet,
  'Fifty Pct Intra Hod Lod':       Target,
  'Flag Pattern':                  Flag,
  'Head And Shoulders':            Hexagon,
  'Hod':                           ArrowUp,
  'How':                           ChevronUp,
  'Ichimoku Cloud':                Cloud,
  'Ict Silver Bullet':             Crosshair,
  'Ihod':                          CircleArrowUp,
  'Ilod':                          CircleArrowDown,
  'Inducement':                    Wand,
  'Initial Balance Breakout':      Maximize2,
  'Internal Pivot Pattern':        GitGraph,
  'Inverse Head And Shoulders':    Pyramid,
  'Kill Zones':                    Focus,
  'Liquidity':                     Droplets,
  'Liquidity Sweep':               Wind,
  'Lod':                           ArrowDown,
  'Low':                           ChevronDown,
  'Macd Price Forecasting':        Radar,
  'Macd Signal':                   Signal,
  'Market Depth':                  Layers,
  'Market Structure Shift':        GitMerge,
  'Mitigation Block':              Shield,
  'Optimal Trade Entry':           Goal,
  'Order Block':                   Boxes,
  'Order Flow Imbalance':          SlidersHorizontal,
  'Pennant Pattern':               FlagTriangleRight,
  'Power Hour Trends':             Bolt,
  'Premium Discount Zones':        Contrast,
  'Range Liquidity':               Ratio,
  'Rising Wedge':                  CornerUpRight,
  'Rounding Bottom':               CircleDot,
  'Rsi Divergence':                Gauge,
  'Session Time':                  Clock,
  'Stochastic Rsi':                Sigma,
  'Supply Demand Zones':           Layers2,
  'Swing Breakout Sequence':       Footprints,
  'Swing Failure Pattern':         Slash,
  'Swing Points':                  Milestone,
  'Symmetrical Triangle':          FlipHorizontal,
  'Three Bar Reversal':            ArrowDownUp,
  'Trailing Stop':                 Lock,
  'Triple Bottom':                 Layers3,
  'Triple Top':                    Mountain,
  'Us Settlement':                 Sunset,
  'Vwap':                          Compass,
  'Wave Consolidation':            Pause,
  'Wyckoff Accumulation':          BarChart,
  'Wyckoff Distribution':          BarChart3,
  'Wyckoff Reaccumulation':        BarChart4,
};

if (process.env.NODE_ENV !== 'production') {
  const values = Object.values(BLOCK_NAME_ICON);
  if (new Set(values).size !== values.length) {
    throw new Error('Duplicate icon component in BLOCK_NAME_ICON (BTCAAAAA-29972 uniqueness gate)');
  }
}

const CATEGORY_ICON: Record<string, LucideIcon> = {
  ELLIOTT_WAVE:     Waves,
  FIBONACCI:        AlignVerticalDistributeCenter,
  INSTITUTIONAL:    Mountain,
  MARKET_STRUCTURE: GitBranch,
  MOVING_AVERAGES:  LineChart,
  OSCILLATORS:      AudioWaveform,
  PATTERNS:         Shapes,
  PRICE_ACTION:     Scaling,
  PRICE_LEVELS:     Magnet,
  RISK_MANAGEMENT:  Shield,
  SESSIONS:         Clock,
  SIGNALS:          Crosshair,
  SMC_ICT:          Boxes,
  SUPPLY_DEMAND:    Layers,
  TREND:            TrendingUp,
  VOLATILITY:       Activity,
  WYCKOFF:          BarChart,
};

export function resolveBlockIcon(name: string, category: string): LucideIcon {
  return BLOCK_NAME_ICON[name] ?? CATEGORY_ICON[category?.toUpperCase()] ?? Blocks;
}
