"""
Test Suite for Strategy: HOD_Rejection
Number: 001
Category: 

Auto-generated by Strategy Builder v1.0
Date: 2026-01-10 11:10:08

Tests cover:
- Strategy initialization
- Block processing
- Confluence calculation
- Entry/exit logic
- Risk management
- Performance tracking
"""

import pytest
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from pathlib import Path

# Import strategy
from src.strategies.strategy_001_hod_rejection import StrategyHodRejection


@pytest.fixture
def sample_ohlcv_data():
    """Generate sample OHLCV data for testing"""
    dates = pd.date_range(start='2024-01-01', periods=200, freq='15min')
    
    # Generate realistic price data
    base_price = 45000
    np.random.seed(42)
    returns = np.random.normal(0, 0.001, 200)
    prices = base_price * (1 + returns).cumprod()
    
    df = pd.DataFrame({
        'timestamp': dates,
        'open': prices * (1 + np.random.uniform(-0.001, 0.001, 200)),
        'high': prices * (1 + np.random.uniform(0, 0.002, 200)),
        'low': prices * (1 + np.random.uniform(-0.002, 0, 200)),
        'close': prices,
        'volume': np.random.uniform(100, 1000, 200)
    })
    
    return df


@pytest.fixture
def strategy_config():
    """Create strategy configuration"""
    return {
        'instrument_id': 'BTC-PERP',
        'timeframe': '15m'
    }


@pytest.fixture
def strategy(strategy_config):
    """Create strategy instance"""
    return StrategyHodRejection(strategy_config)


class TestStrategyInitialization:
    """Test strategy initialization"""
    
    def test_init_creates_strategy(self, strategy):
        """Test strategy is created successfully"""
        assert strategy is not None
        assert strategy.strategy_name == "HOD_Rejection"
        assert strategy.strategy_id == "001_HOD_REJECTION"
    
    def test_init_sets_parameters(self, strategy):
        """Test parameters are set correctly"""
        assert strategy.min_confluence == 70
        assert strategy.max_bars_held == 1000
        assert strategy.risk_per_trade_pct == 1.0
        assert strategy.max_leverage == 2.0
    
    def test_init_creates_blocks(self, strategy):
        """Test building blocks are initialized"""
        assert len(strategy.blocks) == 2
        
        # Check each block
        assert 'hod' in strategy.blocks
        assert strategy.blocks['hod']['weight'] == 20
        assert 'hod' in strategy.blocks
        assert strategy.blocks['hod']['weight'] == 20
    
    def test_init_creates_detectors(self, strategy):
        """Test detectors are initialized"""
        assert len(strategy.detectors) == 2
        
        assert 'hod' in strategy.detectors
        assert strategy.detectors['hod'] is not None
        assert 'hod' in strategy.detectors
        assert strategy.detectors['hod'] is not None


class TestBlockProcessing:
    """Test building block processing"""
    
    def test_analyze_blocks_returns_results(self, strategy, sample_ohlcv_data):
        """Test _analyze_blocks returns results for all blocks"""
        results = strategy._analyze_blocks(sample_ohlcv_data)
        
        assert results is not None
        assert isinstance(results, dict)
        assert len(results) == 2
        
        # Check each block returns a result
        assert 'hod' in results
        assert 'hod' in results
    
    def test_analyze_blocks_handles_insufficient_data(self, strategy):
        """Test analysis handles insufficient data gracefully"""
        # Create minimal dataframe
        df = pd.DataFrame({
            'timestamp': [datetime.now()],
            'open': [45000],
            'high': [45100],
            'low': [44900],
            'close': [45050],
            'volume': [100]
        })
        
        results = strategy._analyze_blocks(df)
        
        # Should not crash, may return INSUFFICIENT_DATA signals
        assert results is not None


class TestConfluenceCalculation:
    """Test confluence calculation"""
    
    def test_calculate_confluence_returns_score_and_signals(self, strategy, sample_ohlcv_data):
        """Test confluence calculation returns both score and signals"""
        results = strategy._analyze_blocks(sample_ohlcv_data)
        
        confluence, signals = strategy._calculate_confluence(results)
        
        assert isinstance(confluence, (int, float))
        assert isinstance(signals, list)
        assert confluence >= 0
        assert confluence <= sum(b['weight'] for b in strategy.blocks.values())
    
    def test_confluence_respects_weights(self, strategy):
        """Test confluence calculation uses configured weights"""
        # Mock results with all signals firing
        mock_results = {}
        mock_results['hod'] = {
            'signal': 'ACTIVE_SIGNAL',
            'confidence': 80
        }
        mock_results['hod'] = {
            'signal': 'ACTIVE_SIGNAL',
            'confidence': 80
        }
        
        confluence, signals = strategy._calculate_confluence(mock_results)
        
        # Total should be sum of all weights when all blocks fire
        max_confluence = sum(b['weight'] for b in strategy.blocks.values())
        assert confluence <= max_confluence


class TestEntryLogic:
    """Test entry logic"""
    
    def test_execute_entry_validates_rr_ratio(self, strategy, sample_ohlcv_data):
        """Test entry validates risk:reward ratio"""
        # Set up mock data
        strategy.bars_data = sample_ohlcv_data.to_dict('records')
        
        # Mock results
        results = strategy._analyze_blocks(sample_ohlcv_data)
        confluence, signals = strategy._calculate_confluence(results)
        
        # Should validate R:R before entry
        initial_trades = strategy.trades_count
        
        # This might or might not enter depending on R:R
        # Just verify it doesn't crash
        try:
            strategy._execute_entry(confluence, results, signals)
        except Exception as e:
            pytest.fail(f"Entry execution failed: {e}")
    
    def test_calculate_tp_sl_returns_valid_levels(self, strategy, sample_ohlcv_data):
        """Test TP/SL calculation returns valid levels"""
        strategy.bars_data = sample_ohlcv_data.to_dict('records')
        results = strategy._analyze_blocks(sample_ohlcv_data)
        
        tp1, tp2, tp3, sl = strategy._calculate_tp_sl(results)
        
        # All levels should be valid numbers
        assert tp1 is not None
        assert tp2 is not None
        assert tp3 is not None
        assert sl is not None
        
        # TP levels should be in correct order
        # (assuming short: tp1 > tp2 > tp3)
        # This test may need adjustment based on strategy direction


class TestRiskManagement:
    """Test risk management"""
    
    def test_calculate_position_size_respects_risk_pct(self, strategy):
        """Test position sizing respects risk percentage"""
        risk_per_unit = 100.0  # $100 risk per unit
        
        quantity = strategy._calculate_position_size(risk_per_unit)
        
        assert quantity is not None
        assert float(quantity) > 0
    
    def test_position_size_scales_with_risk(self, strategy):
        """Test position size scales inversely with risk"""
        small_risk = 50.0
        large_risk = 200.0
        
        qty_small_risk = float(strategy._calculate_position_size(small_risk))
        qty_large_risk = float(strategy._calculate_position_size(large_risk))
        
        # Larger risk should result in smaller position
        assert qty_small_risk > qty_large_risk


class TestPerformanceTracking:
    """Test performance tracking"""
    
    def test_trades_count_increments(self, strategy):
        """Test trades counter increments"""
        initial_count = strategy.trades_count
        
        # Simulate trade
        strategy.trades_count += 1
        
        assert strategy.trades_count == initial_count + 1
    
    def test_win_loss_tracking(self, strategy):
        """Test win/loss tracking"""
        initial_wins = strategy.wins
        initial_losses = strategy.losses
        
        # Simulate win
        strategy.on_position_closed({'pnl': 100})
        assert strategy.wins == initial_wins + 1
        
        # Simulate loss
        strategy.on_position_closed({'pnl': -50})
        assert strategy.losses == initial_losses + 1


class TestDataHandling:
    """Test data handling"""
    
    def test_update_dataframe_maintains_rolling_window(self, strategy, sample_ohlcv_data):
        """Test dataframe maintains rolling window"""
        from nautilus_trader.model.data import Bar
        from nautilus_trader.model.objects import Price, Quantity
        
        # Fill up to max
        for i in range(strategy.max_bars_held + 10):
            # Create mock bar
            row = sample_ohlcv_data.iloc[i % len(sample_ohlcv_data)]
            
            # Simplified bar creation
            strategy.bars_data.append({
                'timestamp': row['timestamp'],
                'open': row['open'],
                'high': row['high'],
                'low': row['low'],
                'close': row['close'],
                'volume': row['volume']
            })
            
            if len(strategy.bars_data) > strategy.max_bars_held:
                strategy.bars_data.pop(0)
        
        # Should not exceed max
        assert len(strategy.bars_data) <= strategy.max_bars_held


class TestEdgeCases:
    """Test edge cases"""
    
    def test_handles_zero_volume_bars(self, strategy):
        """Test strategy handles zero volume bars"""
        df = pd.DataFrame({
            'timestamp': pd.date_range('2024-01-01', periods=10, freq='15min'),
            'open': [45000] * 10,
            'high': [45100] * 10,
            'low': [44900] * 10,
            'close': [45000] * 10,
            'volume': [0] * 10  # Zero volume
        })
        
        # Should not crash
        results = strategy._analyze_blocks(df)
        assert results is not None
    
    def test_handles_flat_price_data(self, strategy):
        """Test strategy handles flat price data"""
        df = pd.DataFrame({
            'timestamp': pd.date_range('2024-01-01', periods=100, freq='15min'),
            'open': [45000] * 100,
            'high': [45000] * 100,
            'low': [45000] * 100,
            'close': [45000] * 100,
            'volume': [100] * 100
        })
        
        # Should not crash
        results = strategy._analyze_blocks(df)
        confluence, signals = strategy._calculate_confluence(results)
        
        assert isinstance(confluence, (int, float))
        assert isinstance(signals, list)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])