"""
Strategy: HOD_Rejection
Number: 001
Category: 
Timeframe: 15-minute
Risk:Reward: 1:3
Author: Strategy Builder v1.0
Date: 2026-01-10 10:53:57

Description:
[DRAFT] Work in progress

Building Blocks Used:
- Hod: 20 points
  * Hod Rejection ()
- Hod: 20 points
  * Bearish ()

Entry Logic:
- Minimum 70 confluence points required

Exit Logic:
- TP1: 1.5R (50% position)
- TP2: 3.0R (30% position) 
- TP3: 5.0R (20% position)
- SL: Pattern invalidation (risk management)

Risk Management:
- Risk per trade: 1.0%
- Max leverage: 2.0x
- Max bars held: 1000
"""

from nautilus_trader.trading.strategy import Strategy
from nautilus_trader.model.data import Bar
from nautilus_trader.model.enums import OrderSide, TimeInForce
from nautilus_trader.model.objects import Quantity, Price
import pandas as pd
from datetime import datetime
from typing import Optional

# Import building blocks
from src.detectors.building_blocks.price_levels.hod import HOD

# Import centralized confluence calculator
from src.strategies.universal_optimizer.modules.confluence_calculator import ConfluenceCalculator


class StrategyHodRejection(Strategy):
    """
    HOD_Rejection
    
    Auto-generated by Strategy Builder v1.0
    Configuration validated and optimized for production use.
    """

# ============================================================================
# OPTIMIZED: 2026-01-10 10:54:01
# Trades: 31, Win Rate: 35.5%, PF: 0.59
# Net PnL: $-1426.85 (-14.27%)
# Fees: $1167.37
# Sharpe: -3.70, Max DD: 0.00%
# ============================================================================

    
    def __init__(self, config):
        super().__init__(config)
        
        # Strategy identification
        self.strategy_id = "001_HOD_REJECTION"
        self.strategy_name = "HOD_Rejection"
        
        # Strategy parameters
        self.min_confluence = 40
        self.max_bars_held = 1000
        self.capital_allocation_pct = 10.0
        
        # Risk management
        self.max_leverage = 2.0
        self.risk_per_trade_pct = 1.0
        self.min_risk_reward = 2.0
        
        # Initialize building blocks
        self.blocks = {}
        self._initialize_blocks()
        
        # Data storage
        self.bars_data = []
        
        # Performance tracking
        self.trades_count = 0
        self.wins = 0
        self.losses = 0
        self.total_confluence_scores = []
        
    def _initialize_blocks(self):
        """Initialize building block detectors"""
        
        # Initialize detector instances
        self.detectors = {
            'hod_0': HOD(timeframe='15min'),
            'hod_1': HOD(timeframe='15min'),
        }
        
        # Block weights configuration
        self.blocks['hod_0'] = {
            'name': 'Hod',
            'weight': 25,
            'enabled': True
        }
        self.blocks['hod_1'] = {
            'name': 'Hod',
            'weight': 25,
            'enabled': True
        }
        
    def _bars_to_dataframe(self, bars) -> pd.DataFrame:
        """Convert Bar objects to DataFrame"""
        return pd.DataFrame([{
            'timestamp': bar.ts_event,
            'open': float(bar.open),
            'high': float(bar.high),
            'low': float(bar.low),
            'close': float(bar.close),
            'volume': float(bar.volume)
        } for bar in bars])
    
    def _update_dataframe(self, bar: Bar) -> pd.DataFrame:
        """Update DataFrame with new bar (rolling window)"""
        self.bars_data.append({
            'timestamp': bar.ts_event,
            'open': float(bar.open),
            'high': float(bar.high),
            'low': float(bar.low),
            'close': float(bar.close),
            'volume': float(bar.volume)
        })
        
        # Keep rolling window
        if len(self.bars_data) > self.max_bars_held:
            self.bars_data.pop(0)
        
        return pd.DataFrame(self.bars_data)
    
    def on_start(self):
        """Initialize strategy"""
        self.log.info(f"{self.strategy_name} starting...")
        self.log.info(f"Strategy ID: {self.strategy_id}")
        self.log.info(f"Min Confluence: {self.min_confluence}")
        self.log.info(f"Min R:R: {self.min_risk_reward}")
        self.log.info(f"Building blocks: 2")
        
        self.log.info(f"Ready for trading")
        
    def on_bar(self, bar: Bar):
        """Process each new bar"""
        # Update DataFrame
        df = self._update_dataframe(bar)
        
        # Skip if insufficient data
        if len(df) < 100:  # Minimum warmup period
            return
        
        # Run building block analysis
        results = self._analyze_blocks(df)
        
        # Calculate confluence
        confluence, signals = self._calculate_confluence(results)
        
        # Track confluence scores
        self.total_confluence_scores.append(confluence)
        
        # Check entry conditions
        if confluence >= self.min_confluence:
            if self.portfolio.is_flat(self.instrument_id):
                self._execute_entry(confluence, results, signals)
                
    def _analyze_blocks(self, df: pd.DataFrame) -> dict:
        """Run all building blocks analysis"""
        results = {}
        
        # Hod
        results['hod_0'] = self.detectors['hod_0'].analyze(df)
        # Hod
        results['hod_1'] = self.detectors['hod_1'].analyze(df)
        
        return results
    
    def _calculate_confluence(self, results: dict) -> tuple:
        """
        Calculate total confluence score using centralized calculator
        Returns: (confluence_score, list_of_signals)
        """
        return ConfluenceCalculator.calculate_confluence(results, self.blocks)
    
    def _execute_entry(self, confluence: int, results: dict, signals: list):
        """Execute trade entry with TP/SL levels"""
        self.log.info(f"🎯 HIGH CONFLUENCE DETECTED: {confluence} points")
        for signal in signals:
            self.log.info(f"  ✓ {signal}")
        
        # Calculate TP/SL levels
        tp1, tp2, tp3, sl = self._calculate_tp_sl(results)
        
        # Verify R:R is acceptable
        current_price = self.bars_data[-1]['close']
        risk = abs(current_price - sl)
        reward = abs(tp2 - current_price)
        
        if risk <= 0:
            self.log.warning("Invalid risk calculation - aborting entry")
            return
        
        rr_ratio = reward / risk
        
        if rr_ratio < self.min_risk_reward:
            self.log.info(f"R:R {rr_ratio:.2f} below minimum {self.min_risk_reward} - skipping")
            return
        
        self.log.info(f"✅ R:R: {rr_ratio:.2f} - ENTERING TRADE")
        
        # Calculate position size
        quantity = self._calculate_position_size(risk)
        
        # Log trade details
        self.log.info(f"Entry: {quantity} @ {current_price}")
        self.log.info(f"TP1: {tp1}, TP2: {tp2}, TP3: {tp3}")
        self.log.info(f"SL: {sl}")
        self.log.info(f"Risk: ${risk:.2f}, Reward: ${reward:.2f}, R:R: {rr_ratio:.2f}")
        
        # Update counters
        self.trades_count += 1
    
    def _calculate_position_size(self, risk_per_unit: float) -> Quantity:
        """Calculate position size based on risk management"""
        account_balance = 10000.0  # Get from portfolio in production
        max_risk_dollars = account_balance * (self.risk_per_trade_pct / 100)
        
        position_size = max_risk_dollars / abs(risk_per_unit)
        position_size = round(position_size, 3)
        
        return Quantity.from_str(str(position_size))
    
    def _calculate_tp_sl(self, results: dict) -> tuple:
        """
        Calculate TP and SL levels
        Returns: (tp1, tp2, tp3, sl)
        """
        current_price = self.bars_data[-1]['close']
        
        # Calculate ATR for dynamic TP/SL
        df = pd.DataFrame(self.bars_data).tail(20)
        df['tr'] = df[['high', 'low', 'close']].apply(
            lambda x: max(x['high'] - x['low'],
                         abs(x['high'] - x['close']),
                         abs(x['low'] - x['close'])), axis=1
        )
        atr = df['tr'].mean()
        
        # Default SL based on ATR
        sl = current_price + (atr * 2.0)  # Adjust based on strategy direction
        
        # TP levels based on R:R targets
        risk = abs(sl - current_price)
        
        tp1 = current_price - (risk * 1.5)  # 1.5R
        tp2 = current_price - (risk * 3.0)  # 3.0R
        tp3 = current_price - (risk * 5.0)  # 5.0R
        
        return tp1, tp2, tp3, sl
    
    def on_position_closed(self, position_data):
        """Track performance when position closes"""
        pnl = position_data.get('pnl', 0)
        
        if pnl > 0:
            self.wins += 1
        else:
            self.losses += 1
        
        # Log performance
        win_rate = (self.wins / self.trades_count * 100) if self.trades_count > 0 else 0
        self.log.info(f"Performance: {self.wins}W / {self.losses}L = {win_rate:.1f}% win rate")
    
    def on_stop(self):
        """Called when strategy stops"""
        self.log.info(f"{self.strategy_name} stopped")
        self.log.info(f"Total trades: {self.trades_count}")
        if self.trades_count > 0:
            win_rate = (self.wins / self.trades_count * 100)
            self.log.info(f"Win rate: {win_rate:.1f}%")