#!/usr/bin/env python3
"""Create a Paperclip alert on nightly CI test failure.

Called from the nightly test workflow when tests fail.  Posts a
`critical`-priority issue to the CTO with the CI run URL.

Usage:
    python scripts/nightly_test_alert.py --workflow <name> --run-id <id> \\
        --run-url <url> [--dry-run]

Exit codes:
    0 — alert issue created
    1 — error
    2 — clean run (no alert created)
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger("nightly_test_alert")

REPO_ROOT = Path(__file__).resolve().parent.parent

CTO_AGENT_ID = "41b5ede6-e209-40ba-b923-dc969c722e6d"
ALERT_LABEL = "nightly-alert"


def _setup_session():
    sys.path.insert(0, str(REPO_ROOT / "src"))
    from touch_index.paperclip_client import _session, _base, _company
    return _session(), _base(), _company()


def create_alert(base_url: str, company_id: str, sess,
                 workflow: str, run_id: str, run_url: str,
                 test_output: str | None, dry_run: bool) -> bool:
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    title = f"Nightly CI Test Failure — {date_str} ({workflow})"

    body = (
        f"**Nightly CI test run failed**\n\n"
        f"- **Workflow:** `{workflow}`\n"
        f"- **Run ID:** `{run_id}`\n"
        f"- **Run URL:** {run_url}\n"
    )
    if test_output:
        body += f"\n### Test Output\n\n```\n{test_output[:5000]}\n```\n"
    body += (
        "\n---\n"
        "_Auto-generated by nightly CI pipeline."
    )

    if dry_run:
        logger.info("DRY RUN: would create alert issue '%s'", title)
        print(json.dumps({"title": title, "description": body, "labels": [ALERT_LABEL],
                          "assigneeAgentId": CTO_AGENT_ID, "priority": "critical"},
                         indent=2))
        return True

    payload = {
        "title": title,
        "description": body,
        "labels": [ALERT_LABEL],
        "assigneeAgentId": CTO_AGENT_ID,
        "priority": "critical",
        "status": "todo",
    }

    try:
        resp = sess.post(
            f"{base_url}/api/companies/{company_id}/issues",
            json=payload,
            timeout=30,
        )
        resp.raise_for_status()
        created = resp.json()
        logger.info(
            "Created alert issue %s: %s",
            created.get("identifier", ""), title,
        )
        return True
    except Exception as exc:
        logger.error("Failed to create alert issue: %s", exc)
        return False


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create Paperclip alert on nightly CI test failure",
    )
    parser.add_argument("--workflow", required=True, help="CI workflow name")
    parser.add_argument("--run-id", required=True, help="CI run ID")
    parser.add_argument("--run-url", required=True, help="CI run URL")
    parser.add_argument("--test-output", default=None,
                        help="Path to file with test output")
    parser.add_argument("--dry-run", action="store_true",
                        help="Log actions without creating issues")
    args = parser.parse_args()

    test_output = None
    if args.test_output:
        path = Path(args.test_output)
        if path.exists():
            test_output = path.read_text()

    sess, base_url, company_id = _setup_session()

    ok = create_alert(
        base_url, company_id, sess,
        args.workflow, args.run_id, args.run_url,
        test_output, args.dry_run,
    )
    if not ok:
        sys.exit(1)

    logger.info("Nightly test alert complete")


if __name__ == "__main__":
    main()
