#!/bin/bash
# rclone-credentials-package.sh — Encrypt rclone.conf + rclone-pass into a
# snapshot's config/rclone/ subtree, using the bootstrap key as the source.
#
# Output layout (under <snap_dir>/config/rclone/):
#   rclone.conf.enc           encrypted rclone.conf (Salted__ openssl format)
#   rclone-pass.enc           encrypted rclone-pass (if present)
#   MANIFEST.json             filenames, sizes, sha256s of ciphertext — NO secrets
#
# Crypto: openssl enc -aes-256-cbc -salt -pbkdf2 -iter 200000
#   - AES-256-CBC: NIST-approved block cipher, 256-bit key.
#   - PBKDF2-HMAC-SHA256, 200,000 iterations: brute-force protection against
#     stolen-snapshot threat model.
#   - Salt is randomly generated by openssl per file and prefixed to the
#     ciphertext ("Salted__" + 8B salt), so two snapshots of the same
#     credential set produce different ciphertexts (defeats known-plaintext
#     pattern matching across snapshots).
#
# Source paths (overridable via env):
#   RCLONE_CONFIG_OVERRIDE   default: $HOME/.config/rclone/rclone.conf
#   RCLONE_PASS_FILE         default: $HOME/.config/rclone/rclone-pass
#
# Destination:
#   SNAP_DIR_CONFIG_RCLONE   default: <snap_dir>/config/rclone
#     (the caller passes this; recovery.sh passes "$snap_dir/config/rclone")
#
# Exit codes:
#   0  success (all available credentials packaged)
#   1  invalid args / missing bootstrap key
#   2  openssl encrypt failed (treat as fatal)
#   3  manifest write failed
#
# Usage:
#   ./scripts/rclone-credentials-package.sh <snap_dir>
#   # or for a custom location:
#   SNAP_DIR_CONFIG_RCLONE=/tmp/foo ./scripts/rclone-credentials-package.sh

set -euo pipefail

: "${HOME:=$(eval echo "~$(id -un 2>/dev/null || echo root)")}"

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"

log()  { printf '[rclone-creds-package] %s\n' "$*"; }
die()  { log "ERROR: $*" >&2; exit "${2:-1}"; }

# Args
if [[ $# -lt 1 ]]; then
  die "usage: $0 <snap_dir>   (writes into <snap_dir>/config/rclone)" 2
fi
SNAP_DIR="$1"
DEST_DIR="${SNAP_DIR_CONFIG_RCLONE:-$SNAP_DIR/config/rclone}"

# Source paths (match recovery.sh's constants)
RCLONE_CONFIG_SRC="${RCLONE_CONFIG:-$HOME/.config/rclone/rclone.conf}"
RCLONE_PASS_SRC="${RCLONE_PASS_FILE:-$HOME/.config/rclone/rclone-pass}"

# Load the bootstrap key path without running the bootstrap CLI. Key creation is
# an explicit operator step so the out-of-band copy is not silently skipped.
# shellcheck source=./rclone-credentials-bootstrap.sh
source "$SCRIPT_DIR/rclone-credentials-bootstrap.sh"
if [[ ! -s "$KEY_FILE" ]]; then
  die "bootstrap key missing at $KEY_FILE — run scripts/rclone-credentials-bootstrap.sh" 1
fi

# Pre-flight
command -v openssl >/dev/null 2>&1 || die "missing dependency: openssl" 1
command -v sha256sum >/dev/null 2>&1 || die "missing dependency: sha256sum" 1

mkdir -p "$DEST_DIR"
chmod 700 "$DEST_DIR"

PBKDF2_ITER=200000

# Track which optional inputs were present and which were missing so the
# caller (recovery.sh) can emit a clear WARN for missing optional files
# without aborting the rest of the snapshot.
PACKAGED=()
SKIPPED=()

encrypt_one() {
  local label="$1"
  local src="$2"
  local out="$3"
  local size_in sha_out size_out

  if [[ ! -f "$src" ]]; then
    log "  SKIP $label: source missing at $src"
    SKIPPED+=("$label")
    return 0
  fi

  size_in="$(stat -c '%s' "$src" 2>/dev/null || echo 0)"

  # -pbkdf2 with high iter count is the brute-force defense; -salt makes
  # two snapshots of the same plaintext produce different ciphertext.
  # -pass file:KEY_FILE keeps the secret out of argv and out of the
  # process table snapshot that tools like ps scrape.
  if ! openssl enc -aes-256-cbc -salt -pbkdf2 -iter "$PBKDF2_ITER" \
        -pass "file:$KEY_FILE" \
        -in "$src" \
        -out "$out" 2>/tmp/rclone-creds-package.err; then
    log "  ERROR encrypting $label — openssl exit $?"
    cat /tmp/rclone-creds-package.err >&2 || true
    rm -f /tmp/rclone-creds-package.err
    return 2
  fi
  rm -f /tmp/rclone-creds-package.err

  chmod 600 "$out"
  size_out="$(stat -c '%s' "$out" 2>/dev/null || echo 0)"
  sha_out="$(sha256sum "$out" 2>/dev/null | awk '{print $1}')"

  PACKAGED+=("$label")

  log "  packaged $label: ${size_in}B -> ${size_out}B (sha256=${sha_out:0:16}...)"
}

log "packaging rclone credentials into $DEST_DIR"
encrypt_one "rclone.conf" "$RCLONE_CONFIG_SRC" "$DEST_DIR/rclone.conf.enc"
encrypt_one "rclone-pass" "$RCLONE_PASS_SRC"   "$DEST_DIR/rclone-pass.enc"

# Derive a separate MAC key from the bootstrap key so CBC ciphertext and its
# metadata are authenticated without putting the bootstrap key in argv.
MAC_KEY="$(printf '%s' 'paperclip:rclone-credentials:manifest-v1' | \
  openssl mac -digest SHA256 -macopt "key:file:$KEY_FILE" HMAC)"
mac_file() {
  local name="$1" size="$2" sha="$3" file="$4"
  {
    printf '%s\0%s\0%s\0' "$name" "$size" "$sha"
    cat "$file"
  } | openssl mac -digest SHA256 -macopt "hexkey:$MAC_KEY" HMAC
}

# ---- Manifest ----
ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
key_fp="$(sha256sum "$KEY_FILE" | awk '{print substr($1,1,16)}')"

json_array() {
  local first=1 item
  printf '['
  for item in "$@"; do
    if [[ $first -eq 0 ]]; then printf ','; fi
    first=0
    printf '"%s"' "$item"
  done
  printf ']'
}

{
  printf '{\n'
  printf '  "schema": "rclone-credentials-package-v1",\n'
  printf '  "createdAt": "%s",\n' "$ts"
  printf '  "bootstrapKeyFingerprint": "%s",\n' "$key_fp"
  printf '  "cipher": "aes-256-cbc",\n'
  printf '  "kdf": "pbkdf2-hmac-sha256",\n'
  printf '  "kdfIterations": %d,\n' "$PBKDF2_ITER"
  printf '  "files": [\n'
  first=1
  for f in "$DEST_DIR"/*.enc; do
    [[ -f "$f" ]] || continue
    name="$(basename "$f")"
    size="$(stat -c '%s' "$f" 2>/dev/null || echo 0)"
    sha="$(sha256sum "$f" | awk '{print $1}')"
    mac="$(mac_file "$name" "$size" "$sha" "$f")"
    if [[ $first -eq 0 ]]; then printf ',\n'; fi
    first=0
    printf '    {"name": "%s", "sizeBytes": %d, "sha256": "%s", "mac": "%s"}' \
      "$name" "$size" "$sha" "$mac"
  done
  printf '\n  ],\n'
  printf '  "packaged": '
  json_array "${PACKAGED[@]}"
  printf ',\n  "skipped":  '
  json_array "${SKIPPED[@]}"
  printf '\n}\n'
} > "$DEST_DIR/MANIFEST.json"
chmod 600 "$DEST_DIR/MANIFEST.json"

log "wrote MANIFEST.json (packaged=${#PACKAGED[@]}, skipped=${#SKIPPED[@]})"

unset PAPERCLIP_RCLONE_BOOTSTRAP_KEY_FILE

exit 0
